org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.1.3
loader_version_range=[47,)

mod_id=vietnamesetelex
mod_name=Vietnamese Telex
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.duox.telex
